repos:
- repo: https://github.com/ambv/black
  rev: 18.9b0
  hooks:
  - id: black
    language_version: python3.6
    exclude: doc/source
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: trailing-whitespace
    exclude: doc/source/
  - id: end-of-file-fixer
    exclude: doc/source/
  - id: flake8
    exclude: doc/source/
    language_version: python3.6
- repo: https://github.com/asottile/pyupgrade
  rev: v1.12.0
  hooks:
  - id: pyupgrade
    exclude: doc/source/
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
  - id: isort
